


mybatis:
  configuration:
    # lower_case のカラム名を camelCase のプロパティにマッピングする
    mapUnderscoreToCamelCase: true
    # マッピング不能なフィールドがあったときの処理。
    # NONE, WARNING, FAILING
    autoMappingUnknownColumnBehavior: WARNING



spring:
  datasource:
    url: jdbc:mysql://localhost/sample
    username: root
    password: ~
    driver-class-name: com.mysql.jdbc.Driver


